/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'tp3' 
 * Target:  'Target 1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "LPC17xx.h"

/* Keil::CMSIS Driver:CAN@1.6.0 */
#define RTE_Drivers_CAN1                /* Driver CAN1 */
#define RTE_Drivers_CAN2                /* Driver CAN2 */
/* Keil::CMSIS Driver:SPI:SSP@2.10.0 */
#define RTE_Drivers_SPI0                /* Driver SPI0 */
#define RTE_Drivers_SPI1                /* Driver SPI1 */
/* Keil::Device:Startup@1.0.0 */
#define RTE_DEVICE_STARTUP_LPC17XX      /* Device Startup for NXP17XX */


#endif /* RTE_COMPONENTS_H */
