/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "imagesIHM.c"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_TEXT_0     (GUI_ID_USER + 0x01)
#define ID_TEXT_1     (GUI_ID_USER + 0x02)
#define ID_TEXT_2     (GUI_ID_USER + 0x03)
#define ID_PROGBAR_0     (GUI_ID_USER + 0x04)
#define ID_PROGBAR_1     (GUI_ID_USER + 0x05)
#define ID_PROGBAR_2     (GUI_ID_USER + 0x06)
#define ID_IMAGE_0     (GUI_ID_USER + 0x07)
#define ID_IMAGE_1     (GUI_ID_USER + 0x08)
#define ID_IMAGE_2     (GUI_ID_USER + 0x09)
#define ID_IMAGE_3     (GUI_ID_USER + 0x0A)
#define ID_IMAGE_4     (GUI_ID_USER + 0x0B)
#define ID_IMAGE_5     (GUI_ID_USER + 0x0C)
#define ID_IMAGE_6     (GUI_ID_USER + 0x0D)
#define ID_IMAGE_7     (GUI_ID_USER + 0x0E)
#define ID_BUTTON_0     (GUI_ID_USER + 0x0F)

#define ID_IMAGE_0_IMAGE_0     0x00
#define ID_IMAGE_1_IMAGE_0     0x01
#define ID_IMAGE_2_IMAGE_0     0x02
#define ID_IMAGE_3_IMAGE_0     0x03
#define ID_IMAGE_4_IMAGE_0     0x04
#define ID_IMAGE_5_IMAGE_0     0x05
#define ID_IMAGE_6_IMAGE_0     0x06
#define ID_IMAGE_7_IMAGE_0     0x07

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
// USER START (Optionally insert additional static data)
extern char windowInstance;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window1", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text1", ID_TEXT_0, 9, 8, 315, 101, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 100, 65, 140, 40, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_2, 100, 150, 160, 40, 0, 0x64, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 424, 70, 42, 123, 1, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_1, 353, 71, 44, 121, 1, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_2, 274, 71, 43, 118, 1, 0x0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 170, 170, 64, 64, 0, 0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_1, 100, 170, 64, 64, 0, 0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_2, 100, 85, 64, 64, 0, 0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_3, 170, 85, 64, 64, 0, 0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_4, 410, 200, 64, 64, 0, 0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_5, 336, 200, 75, 64, 0, 0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_6, 9, 202, 64, 64, 0, 0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_7, 264, 201, 64, 64, 0, 0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 400, 10, 70, 25, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/*********************************************************************
*
*       _GetImageById
*/
static const void * _GetImageById(U32 Id, U32 * pSize) {
  switch (Id) {
  case ID_IMAGE_0_IMAGE_0:
    *pSize = sizeof(_acImage_0);
    return (const void *)_acImage_0;
  case ID_IMAGE_1_IMAGE_0:
    *pSize = sizeof(_acImage_1);
    return (const void *)_acImage_1;
  case ID_IMAGE_2_IMAGE_0:
    *pSize = sizeof(_acImage_2);
    return (const void *)_acImage_2;
  case ID_IMAGE_3_IMAGE_0:
    *pSize = sizeof(_acImage_3);
    return (const void *)_acImage_3;
  case ID_IMAGE_4_IMAGE_0:
    *pSize = sizeof(_acImage_4);
    return (const void *)_acImage_4;
  case ID_IMAGE_5_IMAGE_0:
    *pSize = sizeof(_acImage_5);
    return (const void *)_acImage_5;
  case ID_IMAGE_6_IMAGE_0:
    *pSize = sizeof(_acImage_6);
    return (const void *)_acImage_6;
  case ID_IMAGE_7_IMAGE_0:
    *pSize = sizeof(_acImage_7);
    return (const void *)_acImage_7;
  }
  return NULL;
}

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  const void * pData;
  WM_HWIN      hItem;
  U32          FileSize;
  int          NCode;
  int          Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_32B_1);
    TEXT_SetText(hItem, "Supervision CAN");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_20B_1);
    TEXT_SetText(hItem, "Feux clignotant");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_20B_1);
    TEXT_SetText(hItem, "Phares");
    //
    // Initialization of 'Progbar'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
    PROGBAR_SetFont(hItem, GUI_FONT_6X8);
    //
    // Initialization of 'Image'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
    pData = _GetImageById(ID_IMAGE_0_IMAGE_0, &FileSize);
    IMAGE_SetGIF(hItem, pData, FileSize);
    //
    // Initialization of 'Image'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);
    pData = _GetImageById(ID_IMAGE_1_IMAGE_0, &FileSize);
    IMAGE_SetGIF(hItem, pData, FileSize);
    //
    // Initialization of 'Image'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_2);
    pData = _GetImageById(ID_IMAGE_2_IMAGE_0, &FileSize);
    IMAGE_SetGIF(hItem, pData, FileSize);
    //
    // Initialization of 'Image'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_3);
    pData = _GetImageById(ID_IMAGE_3_IMAGE_0, &FileSize);
    IMAGE_SetGIF(hItem, pData, FileSize);
    //
    // Initialization of 'Image'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_4);
    pData = _GetImageById(ID_IMAGE_4_IMAGE_0, &FileSize);
    IMAGE_SetGIF(hItem, pData, FileSize);
    //
    // Initialization of 'Image'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_5);
    pData = _GetImageById(ID_IMAGE_5_IMAGE_0, &FileSize);
    IMAGE_SetGIF(hItem, pData, FileSize);
    //
    // Initialization of 'Image'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_6);
    pData = _GetImageById(ID_IMAGE_6_IMAGE_0, &FileSize);
    IMAGE_SetGIF(hItem, pData, FileSize);
    //
    // Initialization of 'Image'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_7);
    pData = _GetImageById(ID_IMAGE_7_IMAGE_0, &FileSize);
    IMAGE_SetGIF(hItem, pData, FileSize);
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "Switch");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
				windowInstance=1;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow1
*/
WM_HWIN CreateWindow1(void);
WM_HWIN CreateWindow1(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
